# Generated by Django 3.2.8 on 2021-10-23 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_Address', models.CharField(max_length=250)),
                ('Buyer_Address', models.CharField(max_length=250)),
                ('Seller_Address', models.CharField(max_length=250)),
                ('Amount', models.IntegerField()),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['Completed'],
            },
        ),
        migrations.CreateModel(
            name='Mnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=250)),
                ('IP', models.CharField(max_length=100)),
                ('Port', models.IntegerField()),
            ],
        ),
    ]
