import Head from "next/head";
import { Button, Container, Grid, Icon, Image, Item, Step, Card, Reveal } from "semantic-ui-react";
import styles from "../styles/Home.module.css";
import { Font, Container_Content, Bidding_Header } from "../styles/Styling";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container} style={{marginTop: '-20px'}}>
        <div className={styles.imagebg}>

        </div>
      </div>

      <div style = {{color: 'white', textAlign: 'center', fontSize: 30, marginTop: '-20%'}}>
            <Font style = {{marginBottom: '2%'}}>The ENERGY marketplace</Font>
            <Font>you need is here.</Font>
      </div>

      <div style = {{textAlign: 'center', marginTop: '10%'}}>
      <Link href="/trades" >
          <Button  size = 'huge'>
                <Font>TRADE NOW</Font>
          </Button>
      </Link>
      </div>

      <div className={styles.container}>
        <Container_Content bg={true} style={{marginTop: '22%'}}>  
          <Container>
            <Card.Group itemsPerRow = {3}>

              <Card>
                <Image src = 'https://i.pinimg.com/736x/31/09/50/3109505fe2c7cfdbf451a4d73ac8ec93.jpg' wrapped ui = {false} />
                <Card.Content>
                  <Card.Header>
                    <Font> GUARANTEES PAYMENT ON BOTH ENDS </Font>
                  </Card.Header>
                  <Card.Description>
                    <h4> Our backend automates all monetary and energy transactions to provide security to both parties through the use of smart contracts </h4>
                  </Card.Description>
                </Card.Content>
              </Card>

              <Card>
                <Image src = 'https://img.freepik.com/free-vector/arcade-machine-with-soda-icon-illustration-technology-game-icon-concept-isolated-flat-cartoon-style_138676-1288.jpg?size=338&ext=jpg' wrapped ui = {false} />
                <Card.Content>
                  <Card.Header> 
                    <Font> MAKE YOUR ENERGY WORK FOR YOU </Font>
                  </Card.Header>
                  <Card.Description>
                    <h4> Simply put up your energy for bidding and earn profits from it within a day </h4>
                  </Card.Description>
                </Card.Content>
              </Card>

              <Card>
                <Image src = 'https://img.freepik.com/free-vector/cryotherapy-icon-with-cryosauna-vector_116137-1010.jpg?size=338&ext=jpg' wrapped ui = {false} />
                <Card.Content>
                  <Card.Header>
                    <Font> MULTIPLE BIDS AVAILABLE </Font>
                  </Card.Header>
                  <Card.Description>
                    <h4> Multiple bids to choose from to ensure everyone has a chance to obtain energy </h4>
                  </Card.Description>
                </Card.Content>
              </Card>
            </Card.Group>
          </Container>
          
          <div className={styles.middleimagebg} style = {{ marginTop: '10%' }}></div>

          <Container style = {{marginTop: '9%'}} >
            <Font style = {{ fontSize: 40, marginBottom: '11%', alignItems: 'center'}}> HOW IT WORKS </Font>
            <Item.Group>
              <Item>
                <Item.Image size = 'medium' src = 'https://www.vippng.com/png/detail/178-1786001_pixel-mario-question-mark-block-super-mario-bros.png'/>
                <Item.Content verticalAlign = 'middle' style = {{textAlign: 'left'}}>
                  <Item.Header>
                    <Font style = {{color: 'red'}}> AS A BUYER </Font>
                  </Item.Header>
                  <Item.Description>
                    <h4>1. Place a bid above minimum bid and current highest bid value.</h4>
                    <h4>2. Wait for seller to end transaction and energy will be automatically transferred to you. (provided you remained the highest bid till the end of sale)</h4>
                  </Item.Description>
                </Item.Content>
              </Item>

              <Item>
                <Item.Image size = 'medium' src = 'https://www.vippng.com/png/detail/178-1786001_pixel-mario-question-mark-block-super-mario-bros.png'/>
                <Item.Content verticalAlign = 'middle' style = {{textAlign: 'left'}}>
                  <Item.Header>
                    <Font style = {{color: 'red'}}> AS A SELLER </Font>
                  </Item.Header>
                  <Item.Description>
                    <h4>1. Enter the minimum bid and amount of energy to be sold before creating new sale.</h4>
                    <h4>2. Wait for buyers to bid and you can choose to end the transaction whenever you deem fit by clicking the sell button. Energy will be automatically transferred to buyer and the current highest bid value will be transferred to you. (Do note that only the address that created the energy sale can click the sell button, else there would be a transaction error)</h4>

                  </Item.Description>
                </Item.Content>
              </Item>
            </Item.Group>
          </Container>
        </Container_Content>

      </div>
      <div className={styles.container_I}>
      <div style = {{ marginTop: '100%' }}>
  

      
                          
                            {/* <Font style={{padding: '100px 0 0 0'}}>
                                <Bidding_Header colorchange={true}> How it works</Bidding_Header>
                                <Bidding_Header > Buyer </Bidding_Header>
                            </Font>
                <Container>
                <Step.Group  size = 'massive' widths = '3'>
                    <Step>
                        <Icon name = 'pencil alternate'/>
                        <Step.Content>
                            <Step.Title>Place a bid</Step.Title>
                            <Step.Description>Bid must exceed minimum and current highest bid</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'calendar check outline' />
                        <Step.Content>
                            <Step.Title>Check bid & address</Step.Title>
                            <Step.Description>Ensure highest bid and address have been updated</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'hourglass half' />
                        <Step.Content>
                            <Step.Title>Wait for sale termination</Step.Title>
                            <Step.Description>Ensure you remain highest bidder until sale terminates</Step.Description>
                        </Step.Content>
                    </Step>
                </Step.Group>
                </Container>

                <Font style={{margin: '10px 0 10px 0'}}>
                    <Bidding_Header> Seller </Bidding_Header>
                </Font>

                <Container style={{paddingBottom: 50}}>
                <Step.Group  size = 'medium' widths = '3' >
                    <Step>
                        <Icon name = 'paint brush'/>
                        <Step.Content>
                            <Step.Title>Create new sale</Step.Title>
                            <Step.Description>Enter minimum bid and amount of energy to sell</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'hourglass half' />
                        <Step.Content>
                            <Step.Title>Wait for bids</Step.Title>
                            <Step.Description>Wait for buyers to place their bids</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'money bill alternate outline' />
                        <Step.Content>
                            <Step.Title>Sell</Step.Title>
                            <Step.Description>End sale and receive payment instantly through Metamask</Step.Description>
                        </Step.Content>
                    </Step>
                </Step.Group> */}
                {/* </Container> */}

                </div>
        


      </div>
    </div>
  );
}
