import Head from "next/head";
import { Button, Container, Grid, Icon, Image, Item, Step } from "semantic-ui-react";
import styles from "../styles/Home.module.css";
import { Font, Container_Content, Bidding_Header } from "../styles/Styling";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container} style={{marginTop: '-20px'}}>
        <div className={styles.imagebg}>
          <div className={styles.container_inner}>
            <Button inverted color="teal">
              <Font>TRADE NOW</Font>
            </Button>
          </div>
        </div>
      </div>
      <div className={styles.container}>
        <Container_Content bg={true} style={{marginTop: '100px'}}>
          <Container>
            <Item.Group divided>
              <Item>
                <Item.Image
                  size="medium"
                  src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8e2ee06e-e1ae-46e9-8732-6c06493347f4/d37ej5g-1904e422-1f42-4db3-a321-bc19a5ef6930.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzhlMmVlMDZlLWUxYWUtNDZlOS04NzMyLTZjMDY0OTMzNDdmNFwvZDM3ZWo1Zy0xOTA0ZTQyMi0xZjQyLTRkYjMtYTMyMS1iYzE5YTVlZjY5MzAuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.94GfpAYSXlbOW2ej7f0bfE8YgaT1w8hXy8UJOBAOQLE"
                />
                <Item.Content
                  verticalAlign="middle"
                  style={{'text-align': 'center'}}
                
                >
                  <Font>
                    <p style={{ fontSize: 20 }}> MAKE YOUR ENERGY WORK </p>
                    <p style={{ fontSize: 20 }}> FOR YOU </p>
                  </Font>
                  <h4 style={{ fontSize: 20 }}>
                    Simply put up your energy for bidding and earn{" "}
                  </h4>
                  <h4
                    style={{
                      fontSize: 20,

                    }}
                  >
                    profits from it within a day!
                  </h4>
                </Item.Content>
              </Item>
            </Item.Group>
          </Container>
        </Container_Content>
      </div>
      <div className={styles.container}>
      <Container_Content bg={true} >
          <Container >
            <Item.Group divided>
              <Item>
                <Item.Content
                  verticalAlign="middle"
                  style={{'text-align': 'center'}}
                >
                  <Font>
                    <p style={{ fontSize: 20 }}> GUARANTEES PAYMENT </p>
                    <p style={{ fontSize: 20 }}> THROUGH SMART CONTRACT </p>
                    <p style={{ fontSize: 20 }}> </p>
                  </Font>
                  <h4 style={{ fontSize: 20 }}>
                    Our backend automates all monetary and energy transactions
                    to provide security to both parties
                  </h4>
                </Item.Content>
                <Item.Image
                  
                  size="medium"
                  src="https://thumbs.dreamstime.com/b/piggy-bank-money-pixel-art-cartoon-retro-game-style-set-108981342.jpg"
                />
              </Item>
            </Item.Group>
          </Container>
        </Container_Content>
      </div>
      <div className={styles.container} style={{height: '400px'}}>
      <Container_Content bg={true} >
          <Container>
            <Item.Group divided >
              <Item>
                <Item.Image
                
                  style={{ marginTop: "-100px" }}
                  size="medium"
                  src="http://pixelartmaker-data-78746291193.nyc3.digitaloceanspaces.com/image/6585cedd19b9913.png"
                />
                <Item.Content
                  verticalAlign="small"
                  style={{'text-align': 'center'}}
                >
                  <Font>
                    <p style={{ fontSize: 20 }}> MULTIPLE BIDS AVAILABLE</p>
                    <p style={{ fontSize: 20 }}> </p>
                  </Font>
                  <h4 style={{ fontSize: 20 }}>
                    Multiple bids to choose from to ensure everyone{" "}
                  </h4>
                  <h4 style={{ fontSize: 20, marginTop: "-12px" }}>
                    has a chance to obtain energy
                  </h4>
                </Item.Content>
              </Item>
            </Item.Group>
          </Container>
        </Container_Content>
   
      </div>
      <div className={styles.container_I}>
      <div style = {{
                            backgroundImage: 'url(https://cdn.pixabay.com/photo/2020/06/20/19/17/the-black-background-5322097_1280.jpg)', 
                            backgroundSize: 'cover', 
                            backgroundPosition: 'center', 
                            width: '100%', 
                            height: '100%'
                        }}>
                          
                            <Font style={{padding: '100px 0 0 0'}}>
                                <Bidding_Header colorchange={true}> How it works</Bidding_Header>
                                <Bidding_Header > Buyer </Bidding_Header>
                            </Font>
                <Container>
                <Step.Group  size = 'medium' widths = '3'>
                    <Step>
                        <Icon name = 'pencil alternate'/>
                        <Step.Content>
                            <Step.Title>Place a bid</Step.Title>
                            <Step.Description>Bid must exceed minimum and current highest bid</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'calendar check outline' />
                        <Step.Content>
                            <Step.Title>Check bid & address</Step.Title>
                            <Step.Description>Ensure highest bid and address have been updated</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'hourglass half' />
                        <Step.Content>
                            <Step.Title>Wait for sale termination</Step.Title>
                            <Step.Description>Ensure you remain highest bidder until sale terminates</Step.Description>
                        </Step.Content>
                    </Step>
                </Step.Group>
                </Container>

                <Font style={{margin: '10px 0 10px 0'}}>
                    <Bidding_Header> Seller </Bidding_Header>
                </Font>

                <Container style={{paddingBottom: 50}}>
                <Step.Group  size = 'medium' widths = '3' >
                    <Step>
                        <Icon name = 'paint brush'/>
                        <Step.Content>
                            <Step.Title>Create new sale</Step.Title>
                            <Step.Description>Enter minimum bid and amount of energy to sell</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'hourglass half' />
                        <Step.Content>
                            <Step.Title>Wait for bids</Step.Title>
                            <Step.Description>Wait for buyers to place their bids</Step.Description>
                        </Step.Content>
                    </Step>

                    <Step>
                        <Icon name = 'money bill alternate outline' />
                        <Step.Content>
                            <Step.Title>Sell</Step.Title>
                            <Step.Description>End sale and receive payment instantly through Metamask</Step.Description>
                        </Step.Content>
                    </Step>
                </Step.Group>
                </Container>

                </div>
        


      </div>
    </div>
  );
}
